name: security-and-ci
on:
  workflow_dispatch:

permissions:
    security-events: write

    
jobs:
  defender:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1
      id: msdo

    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
